global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'monitoring'

# Connect Victoria Metrics
remote_write:
  - url: http://victoriametrics:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      max_shards: 30

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'project'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'nodeexporter:9100'
        labels:
          server: "monitoring"
          service: "node_exporter"

      - targets: 
        - 'cadvisor:8080'
        labels:
          server: "monitoring"
          service: "cadvisor"

      - targets: 
        - 'localhost:9090'
        labels:
          server: "monitoring"
          service: "prometheus"

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'blackbox-project'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: 
        - http_2xx
    static_configs:
      - targets:
        - https://google.com #your links
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115 

